# Created by MichaelCurrin
# https://gist.github.com/MichaelCurrin/a698731096f78240f653faf9a9127cba

name: Build and deploy 

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@gh-pages
        with:
          persist-credentials: false
          submodules: true  # TODO remove this if not using submodules in Hexo

      - name: Install 🔧
        run: npm run install

      - name: Build 🏗️
        run: npm build

      - name: Deploy to GH Pages 🚀
        uses: ibdul/ibdul
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
